-- Find out the first name and department name
-- Use employees table and department table

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID;

-- Above query just work but adding table name in front of column name all the time is not efficient
-- We can use table aliase to make this simpler

SELECT e.FIRST_NAME , d.DEPARTMENT_NAME
FROM EMPLOYEES e  -- THIS IS HOW YOU PUT ALIASE FOR TABLE
INNER JOIN DEPARTMENTS d ON e.Department_Id = d.DEPARTMENT_ID ;

-- GET THE FIRST_NAME AND JOB_TITLE
-- USE EMPLOYEES AND JOBS TABLE
-- THE RELATIONSHIP 
SELECT e.FIRST_NAME, j.JOB_TITLE 
FROM EMPLOYEES e
INNER JOIN JOBS j on E.JOB_ID = j.JOB_ID;

-- FIRST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME  
SELECT e.FIRST_NAME, d.DEPARTMENT_NAME, l.CITY, c.COUNTRY_NAME, r.REGION_NAME 
FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN LOCATIONS l   on l.LOCATION_ID = d.LOCATION_ID
INNER JOIN COUNTRIES c   on l.COUNTRY_ID = c.COUNTRY_ID
INNER JOIN REGIONS r     on c.REGION_ID = r.REGION_ID;

-- INNER JOIN
-- INNER JOIN WILL ONLY RETURN THE DATA MATCH IN BOTH TABLES,  
-- ANYTHING DOES NOT MATCH  WILL NOT BE PART OF THE RESULT
SELECT e.FIRST_NAME , d.DEPARTMENT_NAME
FROM EMPLOYEES e  -- THIS IS HOW YOU PUT ALIASE FOR TABLE
INNER JOIN DEPARTMENTS d ON e.Department_Id = d.DEPARTMENT_ID ;

-- tHE RESULT OF ABOVE QUERY IS 106 rather THAN 107
-- bECAUSE ONE WMPLOYEE DOES NOT HAVE DEPARTMENT
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- LEFT OUTER JOIN
-- WHICH EVER TABLE COMES FIRST, IT'S REFERRED AS LEFT TABLE
-- WHICH EVER TABLE COMES AFTER, IT'S REFERRED AS RIGHT TABLE

-- TASK: GET ALL FIRST NAME AND DEPARTMENT NAME 
-- INCLUDING THE EMPLOYEES WITHOUT DEPARTMENT
SELECT e.FIRST_NAME , d.DEPARTMENT_NAME
FROM EMPLOYEES e  -- THIS IS HOW YOU PUT ALIASE FOR TABLE
LEFT OUTER JOIN DEPARTMENTS d ON e.Department_Id = d.DEPARTMENT_ID ;

-- TASK: GET ALL FIRST NAME AND DEPARTMENT NAME 
-- INCLUDING THE EMPLOYEES WITHOUT ANY EMPLOYEE
SELECT e.FIRST_NAME , d.DEPARTMENT_NAME
FROM EMPLOYEES e  -- THIS IS HOW YOU PUT ALIASE FOR TABLE
RIGHT OUTER JOIN DEPARTMENTS d ON e.Department_Id = d.DEPARTMENT_ID ;

-- TASK: GET ALL FIRST NAME AND DEPARTMENT NAME 
-- INCLUDING THE EMPLOYEES WITHOUT ANY EMPLOYEE
-- INCLUDING THE EMPLOYEE WITHOUT ANY DEPARTMENT
SELECT e.FIRST_NAME , d.DEPARTMENT_NAME
FROM EMPLOYEES e  -- THIS IS HOW YOU PUT ALIASE FOR TABLE
FULL OUTER JOIN DEPARTMENTS d ON e.Department_Id = d.DEPARTMENT_ID ;
































