-- find out the highest earner first name in employee table
SELECT MAX(SALARY)FROM EMPLOYEES;

SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE SALARY = 24000;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- USING THE ABOVE QUERY FIND OUT FIRST_NAME, LAST_NAME OF MINIMUM EARNER
SELECT FIRST_NAME , LAST_NAME
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES );

-- USING THE ABOVE QUERY FIND OUT FIRST_NAME, LAST_NAME OF ALL EMPLOYEES ABOVE AVERAGE
SELECT FIRST_NAME , LAST_NAME
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- SECOND MAX SALARY FROM EMPLOYEES TABLE
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY != (SELECT MAX(SALARY)FROM EMPLOYEES);
-- WHERE SALARY != 24000

-- FIND OUT THE NAME OF ABOVE PERSON
SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)FROM EMPLOYEES
                WHERE SALARY != (SELECT MAX(SALARY)FROM EMPLOYEES));

-- HOW TO RETURN MAX AND MIN SALARY IN ONE COLUMN
-- THE COLUMN NAME SHOULD BE RESULT, IT SHOULD HAVE 2 ROWS
SELECT MAX(SALARY) AS RESULT FROM EMPLOYEES
UNION 
SELECT MIN(SALARY) AS RESULT FROM EMPLOYEES;

-- FIND OUT THE NAME OF PEOPLE WHO MAKE 2100, 24000
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY IN (2100,24000);

-- NOW REMOVE THOSE MAX AND MIN SALARY YOU HARD-CODED IN ABOVE QUERY
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) AS RESULT FROM EMPLOYEES
                 UNION 
                 SELECT MIN(SALARY) AS RESULT FROM EMPLOYEES);

/*
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY IN ((SELECT MAX(SALARY) AS RESULT FROM EMPLOYEES)
                 (SELECT MIN(SALARY) AS RESULT FROM EMPLOYEES));
*/




