-- SET OPERATORS
-- UNION ALL, UNION, MINUS, INTERSECT

-- RUN THIS ONLY ONCE 
-- BY SELECTING 
CREATE TABLE FIRST_TABLE AS (
    SELECT FIRST_NAME , SALARY FROM EMPLOYEES 
    WHERE SALARY BETWEEN 10500 AND 13000
    
) ORDER BY 2 ;  

SELECT * FROM first_table;

CREATE TABLE SECOND_TABLE AS (
    SELECT FIRST_NAME , SALARY FROM EMPLOYEES 
    WHERE SALARY BETWEEN 12000 AND 24000
    
) ORDER BY 2 ;  

COMMIT ;

--------------------------------------------------------------------------------

-- UNION ALL

-- COMBINE THE RESULT FROM 2 QUESRY AND WILL NOT REMOVE DUPLICATE WILL NOT SORT
-- BY FIRST COLUMN
-- DUPLICATE HERE MEANS ROW LEVEL DUPLICATION
-- IF 2 ROW ARE DUPLICATED, ALL COLUMN VALUE MUST BE THE SAME
SELECT * FROM FIRST_TABLE
UNION 
SELECT * FROM SECOND_TABLE;

-- LIST 1: Apple, egg, milk, pineapple, bread
-- LIST 2: Milk, bread, oil, walnut

-- UNION ALL -->> apple, egg, milk, pineapple, bread, milk, bread, oil, walnut
-- UNION     -->> apple, bread, egg, milk, pineapple, oil, walnut

-- LIST 1 MINUS LIST 2
  -- LIST 2 HERE IS NO-NO LIST
  -- MINUS  -->> APPLE, EGG, PINEAPPLE

-- LIST 2 MINUS LIST 1
  -- LIST 1 HERE IS NO-NO LIST
  -- MINUS -->> OIL, WALNUT

-- INTERSECT
  -- LIST 1 INTERSECT LIST 2 
    --> ONLY COMMON PART OF BOTH LIST --> MILK, BREAD
    

SELECT * FROM FIRST_TABLE
MINUS
SELECT * FROM SECOND_TABLE;
-----------------------------
SELECT * FROM SECOND_TABLE
MINUS
SELECT * FROM FIRST_TABLE;


SELECT * FROM FIRST_TABLE
INTERSECT
SELECT * FROM SECOND_TABLE;
-----------------------------
SELECT * FROM SECOND_TABLE
MINUS
SELECT * FROM FIRST_TABLE;


